"""remove role enum and migrate data

Revision ID: 002c3ae3c373
Revises: 8553cc8e8a7b
Create Date: 2026-06-29 18:27:32.125549

"""
from typing import Sequence, Union
import sys
import os

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Add scripts directory to path to import seeder
sys.path.append(os.path.join(os.path.dirname(__file__), '../../'))
from scripts.seed_rbac import seed_rbac_from_connection

# revision identifiers, used by Alembic.
revision: str = '002c3ae3c373'
down_revision: Union[str, Sequence[str], None] = '8553cc8e8a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and migrate data."""
    # 1. Run the data migration using the active Alembic connection
    bind = op.get_bind()
    seed_rbac_from_connection(bind)

    # 2. Proceed with schema changes
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_perm_code'), table_name='permissions')
    op.drop_constraint(op.f('permissions_code_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    
    op.drop_index(op.f('idx_audit_actor'), table_name='role_audit_log')
    op.create_index(op.f('ix_role_audit_log_actor_id'), 'role_audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_role_audit_log_user_id'), 'role_audit_log', ['user_id'], unique=False)
    
    op.drop_index(op.f('idx_rp_perm'), table_name='role_permissions')
    op.drop_index(op.f('idx_rp_role'), table_name='role_permissions')
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    
    op.drop_index(op.f('idx_roles_slug'), table_name='roles')
    op.drop_constraint(op.f('roles_slug_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    
    op.drop_index(op.f('idx_user_role_role'), table_name='user_roles')
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    
    op.drop_column('users', 'role')
    
    # Drop the role_enum type from the database
    postgresql.ENUM('ADMIN', 'MANAGER', 'MEMBER', name='role_enum').drop(bind)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    
    # 1. Re-create the role_enum type
    role_enum = postgresql.ENUM('ADMIN', 'MANAGER', 'MEMBER', name='role_enum')
    role_enum.create(bind)

    # 2. Add the column back as nullable=True to avoid crashing on existing data
    op.add_column('users', sa.Column('role', role_enum, autoincrement=False, nullable=True))
    
    # 3. Reverse map roles from system_role_id to the enum
    # Using raw SQL to safely update rows based on the new RBAC structure
    bind.execute(sa.text("""
        UPDATE users 
        SET role = CASE 
            WHEN r.slug = 'super_admin' THEN 'ADMIN'::role_enum
            WHEN r.slug = 'project_mgr' THEN 'MANAGER'::role_enum
            ELSE 'MEMBER'::role_enum
        END
        FROM roles r 
        WHERE users.system_role_id = r.id
    """))
    
    # Set fallback for any users without a system_role_id
    bind.execute(sa.text("UPDATE users SET role = 'MEMBER'::role_enum WHERE role IS NULL"))
    
    # 4. Alter column to be nullable=False now that all rows have a value
    op.alter_column('users', 'role', existing_type=role_enum, nullable=False)

    # 5. Reverse schema index changes
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.create_index(op.f('idx_user_role_role'), 'user_roles', ['role_id'], unique=False)
    
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.create_unique_constraint(op.f('roles_slug_key'), 'roles', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_roles_slug'), 'roles', ['slug'], unique=False)
    
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.create_index(op.f('idx_rp_role'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('idx_rp_perm'), 'role_permissions', ['permission_id'], unique=False)
    
    op.drop_index(op.f('ix_role_audit_log_user_id'), table_name='role_audit_log')
    op.drop_index(op.f('ix_role_audit_log_actor_id'), table_name='role_audit_log')
    op.create_index(op.f('idx_audit_actor'), 'role_audit_log', ['actor_id'], unique=False)
    
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_unique_constraint(op.f('permissions_code_key'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_perm_code'), 'permissions', ['code'], unique=False)
    # ### end Alembic commands ###
