"""add_story_points_to_tasks

Revision ID: 25ffdbc70eda
Revises: 362bc2cf8f40
Create Date: 2026-04-29 21:42:51.293039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ffdbc70eda'
down_revision: Union[str, Sequence[str], None] = '362bc2cf8f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sprints', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('story_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'story_points')
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    # ### end Alembic commands ###
