"""remove_legacy_key_column

Revision ID: 56e858d746f2
Revises: d9a7a5c1e4bf
Create Date: 2026-04-27 21:24:17.213664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e858d746f2'
down_revision: Union[str, Sequence[str], None] = 'd9a7a5c1e4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_key_key'), 'projects', type_='unique')
    op.drop_constraint(op.f('projects_name_key'), 'projects', type_='unique')
    op.drop_constraint(op.f('uq_projects_name'), 'projects', type_='unique')
    op.drop_constraint(op.f('uq_projects_project_key'), 'projects', type_='unique')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_index(op.f('ix_projects_project_key'), 'projects', ['project_key'], unique=True)
    op.drop_column('projects', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_projects_project_key'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_unique_constraint(op.f('uq_projects_project_key'), 'projects', ['project_key'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_projects_name'), 'projects', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('projects_name_key'), 'projects', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('projects_key_key'), 'projects', ['key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
