"""Add task_type and parent_id

Revision ID: 66306846bed7
Revises: ff28dfdaa080
Create Date: 2026-05-25 21:20:31.186473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66306846bed7'
down_revision: Union[str, Sequence[str], None] = 'ff28dfdaa080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_type', sa.String(), nullable=False, server_default='task'))
    op.add_column('tasks', sa.Column('parent_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_tasks_parent_id', 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_parent_id', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ###
