"""add_missing_deleted_at_indexes

Revision ID: 72a9825b0ec2
Revises: 39411915bcb9
Create Date: 2026-06-18 20:32:55.157459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a9825b0ec2'
down_revision: Union[str, Sequence[str], None] = '39411915bcb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_notification_preferences_deleted_at', 'notification_preferences', ['deleted_at'], unique=False)
    op.create_index('idx_task_attachments_deleted_at', 'task_attachments', ['deleted_at'], unique=False)
    op.create_index('idx_task_watchers_deleted_at', 'task_watchers', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_watchers_deleted_at', table_name='task_watchers')
    op.drop_index('idx_task_attachments_deleted_at', table_name='task_attachments')
    op.drop_index('idx_notification_preferences_deleted_at', table_name='notification_preferences')
    # ### end Alembic commands ###
