"""fix_database_schema

Revision ID: 8206cf960184
Revises: 748dbf225c51
Create Date: 2026-03-17 13:14:56.792555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8206cf960184'
down_revision: Union[str, Sequence[str], None] = '748dbf225c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('portfolio_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'programs', 'portfolios', ['portfolio_id'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('description', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('sprint_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'sprint_id')
    op.drop_column('tasks', 'progress')
    op.drop_column('projects', 'risk_level')
    op.drop_column('projects', 'ai_confidence')
    op.drop_column('projects', 'progress')
    op.drop_column('projects', 'description')
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.drop_column('programs', 'portfolio_id')
    # ### end Alembic commands ###
