"""add_detailed_client_fields

Revision ID: d911e4e500d3
Revises: aacbe6a51412
Create Date: 2026-05-01 23:01:55.204979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd911e4e500d3'
down_revision: Union[str, Sequence[str], None] = 'aacbe6a51412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('company', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('type', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'type')
    op.drop_column('clients', 'company')
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###
