"""Add created_by_id to projects and teams

Revision ID: dc871046c84f
Revises: c2c8bdc2345e
Create Date: 2026-07-14 21:11:43.315574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc871046c84f'
down_revision: Union[str, Sequence[str], None] = 'c2c8bdc2345e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_by_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_projects_created_by_users', 'projects', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('teams', sa.Column('created_by_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_teams_created_by_users', 'teams', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_teams_created_by_users', 'teams', type_='foreignkey')
    op.drop_column('teams', 'created_by_id')
    op.drop_constraint('fk_projects_created_by_users', 'projects', type_='foreignkey')
    op.drop_column('projects', 'created_by_id')
    # ### end Alembic commands ###
