"""add_detailed_team_fields

Revision ID: ef3d8b34c69e
Revises: 313b77ce5fb7
Create Date: 2026-05-01 22:53:58.317421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3d8b34c69e'
down_revision: Union[str, Sequence[str], None] = '313b77ce5fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('description', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('capacity', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('velocity', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('project_manager_id', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('lead_id', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('product_manager_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['lead_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'teams', 'users', ['project_manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'teams', 'users', ['product_manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'product_manager_id')
    op.drop_column('teams', 'lead_id')
    op.drop_column('teams', 'project_manager_id')
    op.drop_column('teams', 'velocity')
    op.drop_column('teams', 'capacity')
    op.drop_column('teams', 'description')
    # ### end Alembic commands ###
