"""add is_milestone to tasks

Revision ID: ff28dfdaa080
Revises: fuse_999_and_c7a1e3
Create Date: 2026-05-25 19:53:51.981050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff28dfdaa080'
down_revision: Union[str, Sequence[str], None] = 'fuse_999_and_c7a1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'labels', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_groups', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('is_milestone', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_milestone')
    op.drop_constraint(None, 'task_groups', type_='foreignkey')
    op.drop_constraint(None, 'labels', type_='foreignkey')
    # ### end Alembic commands ###
